
export const GET_MOVIE_LIST_REQUEST = 'GET_MOVIE_LIST_REQUEST';
export const GET_MOVIE_LIST_SUCCESS = 'GET_MOVIE_LIST_SUCCESS';
export const GET_MOVIE_LIST_FAILURE = 'GET_MOVIE_LIST_FAILURE';

export const GET_MOVIE_DETAILS_REQUEST = 'GET_MOVIE_DETAILS_REQUEST';
export const GET_MOVIE_DETAILS_SUCCESS = 'GET_MOVIE_DETAILS_SUCCESS';
export const GET_MOVIE_DETAILS_FAILURE = 'GET_MOVIE_DETAILS_FAILURE';