
export const GET_MOVIE_LIST_REQUEST = 'GET_MOVIE_LIST_REQUEST';
export const GET_MOVIE_LIST_SUCCESS = 'GET_MOVIE_LIST_SUCCESS';
export const GET_MOVIE_LIST_FAILURE = 'GET_MOVIE_LIST_FAILURE';

export const GET_MOVIE_DETAILS_REQUEST = 'GET_MOVIE_DETAILS_REQUEST';
export const GET_MOVIE_DETAILS_SUCCESS = 'GET_MOVIE_DETAILS_SUCCESS';
export const GET_MOVIE_DETAILS_FAILURE = 'GET_MOVIE_DETAILS_FAILURE';

export const ADD_MOVIE_TO_FAVOURITE_LIST = 'ADD_MOVIE_TO_FAVOURITE_LIST';

export const DELETE_MOVIE_FROM_FAVOURITE_LIST = 'DELETE_MOVIE_FROM_FAVOURITE_LIST';

export const SET_MOVIE_REDUCER = 'SET_MOVIE_REDUCER';

export const SEARCH_MOVIE_REQUEST = 'SEARCH_MOVIE_REQUEST';
export const SEARCH_MOVIE_SUCCESS = 'SEARCH_MOVIE_SUCCESS';
export const SEARCH_MOVIE_FAILURE = 'SEARCH_MOVIE_FAILURE';